# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-client
  pod 'Firebase/Auth'
  pod 'JGProgressHUD','~>2.0.3'

  target 'ios-clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-clientUITests' do
    # Pods for testing
  end

end
