# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_node_server:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/bucket-list

    steps:
      - checkout

      - run:
          name: testing node version
          command: node --version
      - run:
          name: testing npm version
          command: npm --version

      - run:
          name: updating npm...
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi

      - run:
          name: testing node version after update
          command: node --version
      - run:
          name: testing npm version after update
          command: npm --version

      - run:
          name: npm-install
          command: |
                cd node-server
                npm install

      - run:
          name: npm-start
          command: |
                cd node-server
                npm start
workflows:
  version: 2
  node_server:
    jobs:
      - build_node_server
