# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_node_server:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/bucket-list

    steps:
      - checkout

      - run:
          name: npm install
          command: |
            cd node-server
            npm install

      - run:
          name: setup firebase config
          command: |
            cd node-server
            cd conf
            echo $FIREBASE_CONFIG > bucketlistFirebase.json

      - run:
          name: setup secret keys
          command: |
            cd node-server
            cd conf
            echo $SECRET_KEYS > secret-keys.js

      - run:
          name: npm start and test
          command: |
            cd node-server
            npm start

workflows:
  version: 2
  node_server:
    jobs:
      - build_node_server:
          context: node-server
